import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 */

const sidebars: SidebarsConfig = {
  // Main sidebar for the book
  modulesSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module1-ros2',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-02-digital-twin',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3-ai-robot-brain',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4-vla',
        },
      ],
      collapsed: false,
    },
    {
      type: 'doc',
      id: 'glossary',
      label: 'Glossary',
    },
  ],
};

export default sidebars;
